#ifndef BONES_H
#define BONES_H

enum BONE {
	BONE_ROOT,
	BONE_HIPS,
	BONE_SPINE1,
	BONE_SPINE2,
	BONE_SPINE3,
	BONE_NECK1,
	BONE_NECK2,
	BONE_HEAD,

	BONE_LEFT_CLAVICLE,
	BONE_LEFT_SHOULDER,
	BONE_LEFT_ARM,
	BONE_LEFT_FOREARM,
	BONE_LEFT_HAND,
	BONE_LEFT_THUMB1,
	BONE_LEFT_THUMB2,
	BONE_LEFT_THUMB3,
	BONE_LEFT_INDEX1,
	BONE_LEFT_INDEX2,
	BONE_LEFT_INDEX3,
	BONE_LEFT_MIDDLE1,
	BONE_LEFT_MIDDLE2,
	BONE_LEFT_MIDDLE3,
	BONE_LEFT_RING1,
	BONE_LEFT_RING2,
	BONE_LEFT_RING3,
	BONE_LEFT_PINKY1,
	BONE_LEFT_PINKY2,
	BONE_LEFT_PINKY3,

	BONE_RIGHT_CLAVICLE,
	BONE_RIGHT_SHOULDER,
	BONE_RIGHT_ARM,
	BONE_RIGHT_FOREARM,
	BONE_RIGHT_HAND,
	BONE_RIGHT_THUMB1,
	BONE_RIGHT_THUMB2,
	BONE_RIGHT_THUMB3,
	BONE_RIGHT_INDEX1,
	BONE_RIGHT_INDEX2,
	BONE_RIGHT_INDEX3,
	BONE_RIGHT_MIDDLE1,
	BONE_RIGHT_MIDDLE2,
	BONE_RIGHT_MIDDLE3,
	BONE_RIGHT_RING1,
	BONE_RIGHT_RING2,
	BONE_RIGHT_RING3,
	BONE_RIGHT_PINKY1,
	BONE_RIGHT_PINKY2,
	BONE_RIGHT_PINKY3,

	BONE_LEFT_THIGH,
	BONE_LEFT_LEG,
	BONE_LEFT_FOOT,
	BONE_LEFT_TOES,

	BONE_RIGHT_THIGH,
	BONE_RIGHT_LEG,
	BONE_RIGHT_FOOT,
	BONE_RIGHT_TOES,

	BONE_ROLL	= 0x100,
};
BONE operator|(BONE a, BONE b) { return BONE(int(a) | int(b)); }

uint8 bone_parents[] = {
	BONE_ROOT,
	BONE_ROOT,					//BONE_HIPS,

	BONE_HIPS,					//BONE_SPINE1,
	BONE_SPINE1,				//BONE_SPINE2,
	BONE_SPINE2,				//BONE_SPINE3,
	BONE_SPINE3,				//BONE_NECK1,
	BONE_NECK1,					//BONE_NECK2,
	BONE_NECK2,					//BONE_HEAD,

	BONE_SPINE2,				//BONE_LEFT_CLAVICLE,
	BONE_LEFT_CLAVICLE,			//BONE_LEFT_SHOULDER,
	BONE_LEFT_SHOULDER,			//BONE_LEFT_ARM,
	BONE_LEFT_ARM,				//BONE_LEFT_FOREARM,
	BONE_LEFT_FOREARM,			//BONE_LEFT_HAND,
	BONE_LEFT_HAND,				//BONE_LEFT_THUMB1,
	BONE_LEFT_THUMB1,			//BONE_LEFT_THUMB2,
	BONE_LEFT_THUMB2,			//BONE_LEFT_THUMB3,
	BONE_LEFT_HAND,				//BONE_LEFT_INDEX1,
	BONE_LEFT_INDEX1,			//BONE_LEFT_INDEX2,
	BONE_LEFT_INDEX2,			//BONE_LEFT_INDEX3,
	BONE_LEFT_HAND,				//BONE_LEFT_MIDDLE1,
	BONE_LEFT_MIDDLE1,			//BONE_LEFT_MIDDLE2,
	BONE_LEFT_MIDDLE2,			//BONE_LEFT_MIDDLE3,
	BONE_LEFT_HAND,				//BONE_LEFT_RING1,
	BONE_LEFT_RING1,			//BONE_LEFT_RING2,
	BONE_LEFT_RING2,			//BONE_LEFT_RING3,
	BONE_LEFT_HAND,				//BONE_LEFT_PINKY1,
	BONE_LEFT_PINKY1,			//BONE_LEFT_PINKY2,
	BONE_LEFT_PINKY2,			//BONE_LEFT_PINKY3,

	BONE_SPINE2,				//BONE_RIGHT_CLAVICLE,
	BONE_RIGHT_CLAVICLE,		//BONE_RIGHT_SHOULDER,
	BONE_RIGHT_SHOULDER,		//BONE_RIGHT_ARM,
	BONE_RIGHT_ARM,				//BONE_RIGHT_FOREARM,
	BONE_RIGHT_FOREARM,			//BONE_RIGHT_HAND,
	BONE_RIGHT_HAND,			//BONE_RIGHT_THUMB1,
	BONE_RIGHT_THUMB1,			//BONE_RIGHT_THUMB2,
	BONE_RIGHT_THUMB2,			//BONE_RIGHT_THUMB3,
	BONE_RIGHT_HAND,			//BONE_RIGHT_INDEX1,
	BONE_RIGHT_INDEX1,			//BONE_RIGHT_INDEX2,
	BONE_RIGHT_INDEX2,			//BONE_RIGHT_INDEX3,
	BONE_RIGHT_HAND,			//BONE_RIGHT_MIDDLE1,
	BONE_RIGHT_MIDDLE1,			//BONE_RIGHT_MIDDLE2,
	BONE_RIGHT_MIDDLE2,			//BONE_RIGHT_MIDDLE3,
	BONE_RIGHT_HAND,			//BONE_RIGHT_RING1,
	BONE_RIGHT_RING1,			//BONE_RIGHT_RING2,
	BONE_RIGHT_RING2,			//BONE_RIGHT_RING3,
	BONE_RIGHT_HAND,			//BONE_RIGHT_PINKY1,
	BONE_RIGHT_PINKY1,			//BONE_RIGHT_PINKY2,
	BONE_RIGHT_PINKY2,			//BONE_RIGHT_PINKY3,

	BONE_HIPS,					//BONE_LEFT_THIGH,
	BONE_LEFT_THIGH,			//BONE_LEFT_LEG,
	BONE_LEFT_LEG,				//BONE_LEFT_FOOT,
	BONE_LEFT_FOOT,				//BONE_LEFT_TOES,

	BONE_HIPS,					//BONE_RIGHT_THIGH,
	BONE_RIGHT_THIGH,			//BONE_RIGHT_LEG,
	BONE_RIGHT_LEG,				//BONE_RIGHT_FOOT,
	BONE_RIGHT_FOOT,			//BONE_RIGHT_TOES,
};

const char *bone_names[] = {
	"root",			//BONE_ROOT,
	"hips",			//BONE_HIPS,
	"spine1",		//BONE_SPINE1,
	"spine2",		//BONE_SPINE2,
	"spine3",		//BONE_SPINE3,
	"neck1",		//BONE_NECK1,
	"neck2",		//BONE_NECK2,
	"head",			//BONE_HEAD,

	"Lclavicle",	//BONE_LEFT_CLAVICLE,
	"Lshoulder",	//BONE_LEFT_SHOULDER,
	"Larm",			//BONE_LEFT_ARM,
	"Lforearm",		//BONE_LEFT_FOREARM,
	"Lhand",		//BONE_LEFT_HAND,
	"Lthumb1",		//BONE_LEFT_THUMB1,
	"Lthumb2",		//BONE_LEFT_THUMB2,
	"Lthumb3",		//BONE_LEFT_THUMB3,
	"Lindex1",		//BONE_LEFT_INDEX1,
	"Lindex2",		//BONE_LEFT_INDEX2,
	"Lindex3",		//BONE_LEFT_INDEX3,
	"Lmiddle1",		//BONE_LEFT_MIDDLE1,
	"Lmiddle2",		//BONE_LEFT_MIDDLE2,
	"Lmiddle3",		//BONE_LEFT_MIDDLE3,
	"Lring1",		//BONE_LEFT_RING1,
	"Lring2",		//BONE_LEFT_RING2,
	"Lring3",		//BONE_LEFT_RING3,
	"Lpinky1",		//BONE_LEFT_PINKY1,
	"Lpinky2",		//BONE_LEFT_PINKY2,
	"Lpinky3",		//BONE_LEFT_PINKY3,

	"Rclavicle",	//BONE_RIGHT_CLAVICLE,
	"Rshoulder",	//BONE_RIGHT_SHOULDER,
	"Rarm",			//BONE_RIGHT_ARM,
	"Rforearm",		//BONE_RIGHT_FOREARM,
	"Rhand",		//BONE_RIGHT_HAND,
	"Rthumb1",		//BONE_RIGHT_THUMB1,
	"Rthumb2",		//BONE_RIGHT_THUMB2,
	"Rthumb3",		//BONE_RIGHT_THUMB3,
	"Rindex1",		//BONE_RIGHT_INDEX1,
	"Rindex2",		//BONE_RIGHT_INDEX2,
	"Rindex3",		//BONE_RIGHT_INDEX3,
	"Rmiddle1",		//BONE_RIGHT_MIDDLE1,
	"Rmiddle2",		//BONE_RIGHT_MIDDLE2,
	"Rmiddle3",		//BONE_RIGHT_MIDDLE3,
	"Rring1",		//BONE_RIGHT_RING1,
	"Rring2",		//BONE_RIGHT_RING2,
	"Rring3",		//BONE_RIGHT_RING3,
	"Rpinky1",		//BONE_RIGHT_PINKY1,
	"Rpinky2",		//BONE_RIGHT_PINKY2,
	"Rpinky3",		//BONE_RIGHT_PINKY3,

	"Lthigh",		//BONE_LEFT_THIGH,
	"Lleg",			//BONE_LEFT_LEG,
	"Lfoot",		//BONE_LEFT_FOOT,
	"Ltoes",		//BONE_LEFT_TOES,

	"Rthigh",		//BONE_RIGHT_THIGH,
	"Rleg",			//BONE_RIGHT_LEG,
	"Rfoot",		//BONE_RIGHT_FOOT,
	"Rtoes",		//BONE_RIGHT_TOES,
};

struct BoneMapping {
	const char *name;
	BONE		bone;
};

BoneMapping kaydara_bones[] = {
	{"Humanoid:Hips",				BONE_HIPS							},
	{"Humanoid:Spine",				BONE_SPINE1							},
	{"Humanoid:Spine1",				BONE_SPINE2							},
	{"Humanoid:Spine2",				BONE_SPINE3							},
	{"Humanoid:Neck",				BONE_NECK1							},
	{"Humanoid:Head",				BONE_HEAD							},
	{"Humanoid:LeftShoulder",		BONE_LEFT_SHOULDER					},
	{"Humanoid:LeftArm",			BONE_LEFT_ARM						},
	{"Humanoid:LeftArmRoll",		BONE_LEFT_ARM |  BONE_ROLL			},
	{"Humanoid:LeftForeArm",		BONE_LEFT_FOREARM					},
	{"Humanoid:LeftForeArmRoll",	BONE_LEFT_FOREARM | BONE_ROLL		},
	{"Humanoid:LeftHand",			BONE_LEFT_HAND						},
	{"Humanoid:LeftThumb1",			BONE_LEFT_THUMB1					},
	{"Humanoid:LeftThumb2",			BONE_LEFT_THUMB2					},
	{"Humanoid:LeftThumb3",			BONE_LEFT_THUMB3					},
	{"Humanoid:LeftIndex1",			BONE_LEFT_INDEX1					},
	{"Humanoid:LeftIndex2",			BONE_LEFT_INDEX2					},
	{"Humanoid:LeftIndex3",			BONE_LEFT_INDEX3					},
	{"Humanoid:LeftMiddle1",		BONE_LEFT_MIDDLE1					},
	{"Humanoid:LeftMiddle2",		BONE_LEFT_MIDDLE2					},
	{"Humanoid:LeftMiddle3",		BONE_LEFT_MIDDLE3					},
	{"Humanoid:LeftRing1",			BONE_LEFT_RING1						},
	{"Humanoid:LeftRing2",			BONE_LEFT_RING2						},
	{"Humanoid:LeftRing3",			BONE_LEFT_RING3						},
	{"Humanoid:LeftPinky1",			BONE_LEFT_PINKY1					},
	{"Humanoid:LeftPinky2",			BONE_LEFT_PINKY2					},
	{"Humanoid:LeftPinky3",			BONE_LEFT_PINKY3					},
	{"Humanoid:RightShoulder",		BONE_RIGHT_SHOULDER					},
	{"Humanoid:RightArm",			BONE_RIGHT_ARM						},
	{"Humanoid:RightArmRoll",		BONE_RIGHT_ARM | BONE_ROLL			},
	{"Humanoid:RightForeArm",		BONE_RIGHT_FOREARM					},
	{"Humanoid:RightForeArmRoll",	BONE_RIGHT_FOREARM | BONE_ROLL		},
	{"Humanoid:RightHand",			BONE_RIGHT_HAND						},
	{"Humanoid:RightThumb1",		BONE_RIGHT_THUMB1					},
	{"Humanoid:RightThumb2",		BONE_RIGHT_THUMB2					},
	{"Humanoid:RightThumb3",		BONE_RIGHT_THUMB3					},
	{"Humanoid:RightIndex1",		BONE_RIGHT_INDEX1					},
	{"Humanoid:RightIndex2",		BONE_RIGHT_INDEX2					},
	{"Humanoid:RightIndex3",		BONE_RIGHT_INDEX3					},
	{"Humanoid:RightMiddle1",		BONE_RIGHT_MIDDLE1					},
	{"Humanoid:RightMiddle2",		BONE_RIGHT_MIDDLE2					},
	{"Humanoid:RightMiddle3",		BONE_RIGHT_MIDDLE3					},
	{"Humanoid:RightRing1",			BONE_RIGHT_RING1					},
	{"Humanoid:RightRing2",			BONE_RIGHT_RING2					},
	{"Humanoid:RightRing3",			BONE_RIGHT_RING3					},
	{"Humanoid:RightPinky1",		BONE_RIGHT_PINKY1					},
	{"Humanoid:RightPinky2",		BONE_RIGHT_PINKY2					},
	{"Humanoid:RightPinky3",		BONE_RIGHT_PINKY3					},
	{"Humanoid:LeftUpLeg",			BONE_LEFT_THIGH						},
	{"Humanoid:LeftUpLegRoll",		BONE_LEFT_THIGH | BONE_ROLL			},
	{"Humanoid:LeftLeg",			BONE_LEFT_LEG						},
	{"Humanoid:LeftLegRoll",		BONE_LEFT_LEG | BONE_ROLL			},
	{"Humanoid:LeftFoot",			BONE_LEFT_FOOT						},
	{"Humanoid:LeftToes",			BONE_LEFT_TOES						},
	{"Humanoid:RightUpLeg",			BONE_RIGHT_THIGH					},
	{"Humanoid:RightUpLegRoll",		BONE_RIGHT_THIGH | BONE_ROLL		},
	{"Humanoid:RightLeg",			BONE_RIGHT_LEG						},
	{"Humanoid:RightLegRoll",		BONE_RIGHT_LEG | BONE_ROLL			},
	{"Humanoid:RightFoot",			BONE_RIGHT_FOOT						},
	{"Humanoid:RightToes",			BONE_RIGHT_TOES						},
};

BoneMapping humanoid_bones[] = {
	{"Pelvis",						BONE_HIPS							},
	{"R_Thigh",						BONE_RIGHT_THIGH					},
	{"R_Leg",						BONE_RIGHT_LEG						},
	{"R_Foot",						BONE_RIGHT_FOOT						},
	{"R_Toe",						BONE_RIGHT_TOES						},
	{"L_Thigh",						BONE_LEFT_THIGH						},
	{"L_Leg",						BONE_LEFT_LEG						},
	{"L_Foot",						BONE_LEFT_FOOT						},
	{"L_Toe",						BONE_LEFT_TOES						},
	{"Spine_0",						BONE_SPINE1							},
	{"Spine_1",						BONE_SPINE2							},
	{"Spine_2",						BONE_SPINE3							},
	{"R_Clavicle",					BONE_RIGHT_CLAVICLE					},
	{"R_Shoulder",					BONE_RIGHT_SHOULDER					},
	{"R_Forearm",					BONE_RIGHT_FOREARM					},
	{"R_ForearmRoll",				BONE_RIGHT_FOREARM | BONE_ROLL		},
	{"R_Hand",						BONE_RIGHT_HAND						},
	{"R_Index_A",					BONE_RIGHT_INDEX1					},
	{"R_Middle_A",					BONE_RIGHT_MIDDLE1					},
	{"R_Thumb_B",					BONE_RIGHT_THUMB2					},
	{"L_Clavicle",					BONE_LEFT_CLAVICLE					},
	{"L_Shoulder",					BONE_LEFT_SHOULDER					},
	{"L_Forearm",					BONE_LEFT_FOREARM					},
	{"L_ForearmRoll",				BONE_LEFT_FOREARM | BONE_ROLL		},
	{"L_Hand",						BONE_LEFT_HAND						},
	{"L_Index_A",					BONE_LEFT_INDEX1					},
	{"L_Middle_A",					BONE_LEFT_MIDDLE1					},
	{"L_Thumb_B",					BONE_LEFT_THUMB2					},
	{"Neck_1",						BONE_NECK1							},
	{"Head",						BONE_HEAD							},
};


#endif BONES_H
