//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by ORBIScrude.rc
//
#define IDI_ISOPOD                      100
#define IDR_TOOLBAR_START               101
#define IDR_TOOLBAR_LICENSE             102
#define IDR_TOOLBAR_NAV                 105
#define IDB_SETTINGS                    107
#define IDR_ACCELERATOR_SETTINGS        201
#define IDC_TARGET                      300
#define ID_ORBISCRUDE_HOME              40001
#define ID_ORBISCRUDE_SETTINGS          40002
#define ID_ORBISCRUDE_LICENSE           40003
#define ID_ORBISCRUDE_HELP              40004
#define ID_ORBISCRUDE_GRAB              40005
#define ID_ORBISCRUDE_PAUSE             40006
#define ID_ORBISCRUDE_GRAB_RESUME       40007
#define ID_ORBISCRUDE_GRAB_UNTILHALT    40008
#define ID_ORBISCRUDE_GRAB_PAUSEAFTERCAP 40009
#define ID_ORBISCRUDE_GRAB_TARGETS      40100
#define ID_ORBISCRUDE_GRAB_PS3          (ID_ORBISCRUDE_GRAB_TARGETS+0)
#define ID_ORBISCRUDE_GRAB_PS4          (ID_ORBISCRUDE_GRAB_TARGETS+1)
#define ID_ORBISCRUDE_GRAB_DX12         (ID_ORBISCRUDE_GRAB_TARGETS+2)
#define ID_ORBISCRUDE_GRAB_DX11         (ID_ORBISCRUDE_GRAB_TARGETS+3)
#define ID_ORBISCRUDE_GRAB_WII          (ID_ORBISCRUDE_GRAB_TARGETS+4)
#define ID_ORBISCRUDE_GRAB_XONE         (ID_ORBISCRUDE_GRAB_TARGETS+5)
#define ID_ORBISCRUDE_GRAB_X64          (ID_ORBISCRUDE_GRAB_TARGETS+6)
#define ID_ORBISCRUDE_GRAB_TARGETS_MAX  (ID_ORBISCRUDE_GRAB_TARGETS+9)
#define ID_ORBISCRUDE_GRAB_FRAMES       40200
#define ID_ORBISCRUDE_GRAB_FRAMES1      (ID_ORBISCRUDE_GRAB_FRAMES+1)
#define ID_ORBISCRUDE_GRAB_FRAMES2      (ID_ORBISCRUDE_GRAB_FRAMES+2)
#define ID_ORBISCRUDE_GRAB_FRAMES3      (ID_ORBISCRUDE_GRAB_FRAMES+3)
#define ID_ORBISCRUDE_GRAB_FRAMES4      (ID_ORBISCRUDE_GRAB_FRAMES+4)
#define ID_ORBISCRUDE_GRAB_FRAMES5      (ID_ORBISCRUDE_GRAB_FRAMES+5)
#define ID_ORBISCRUDE_GRAB_FRAMES6      (ID_ORBISCRUDE_GRAB_FRAMES+6)
#define ID_ORBISCRUDE_GRAB_FRAMES7      (ID_ORBISCRUDE_GRAB_FRAMES+7)
#define ID_ORBISCRUDE_GRAB_FRAMES8      (ID_ORBISCRUDE_GRAB_FRAMES+8)

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        204
#define _APS_NEXT_COMMAND_VALUE         40400
#define _APS_NEXT_CONTROL_VALUE         1001
#define _APS_NEXT_SYMED_VALUE           300
#endif
#endif
