
#define IDR_MENU_SUBMENUS               200
#define IDR_ACCELERATOR_TEXT            300
#define ID_EDIT                         40400
#define ID_EDIT_WORDWRAP                40401
#define ID_EDIT_DELETE                  40402
#define ID_EDIT_DELETE_FWD				40403
#define ID_EDIT_FINDNEXT                40404
#define ID_EDIT_FINDPREV                40405
#define ID_EDIT_SELECT                  40406
#define ID_FILE_SAVE                    0xE000
#define ID_FILE_OPEN                    0xE001
#define ID_FILE_SAVEAS                  0xE002
#define ID_FILE_OPENFOLDER				0xE080
#define ID_EDIT_CLEAR                   0xE120
#define ID_EDIT_CLEAR_ALL               0xE121
#define ID_EDIT_COPY                    0xE122
#define ID_EDIT_CUT                     0xE123
#define ID_EDIT_FIND                    0xE124
#define ID_EDIT_PASTE                   0xE125
#define ID_EDIT_PASTE_LINK              0xE126
#define ID_EDIT_PASTE_SPECIAL           0xE127
#define ID_EDIT_REPEAT                  0xE128
#define ID_EDIT_REPLACE                 0xE129
#define ID_EDIT_SELECT_ALL              0xE12A
#define ID_EDIT_UNDO                    0xE12B
#define ID_EDIT_REDO                    0xE12C
#define ID_APP_ABOUT                    0xE140
#define ID_APP_EXIT                     0xE141
#define ID_PREV_PANE                    0xE142
#define ID_NEXT_PANE                    0xE143
